<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationIcon>Assets\appicon.ico</ApplicationIcon>
    <AssemblyName>PlumbobForge-Setup</AssemblyName>
    <AssemblyTitle>PlumbobForge Installer</AssemblyTitle>
    <Description>PlumbobForge Installer</Description>
    <Product>PlumbobForge</Product>
    <Company>bringscookies</Company>
    <Authors>bringscookies</Authors>
    <Version>1.0.3</Version>
    <FileVersion>1.0.3.0</FileVersion>
    <InformationalVersion>1.0.3</InformationalVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <RetainVM>false</RetainVM>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SelfContained)' == 'true'">
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.5" />
    <PackageReference Include="Avalonia.Win32" Version="11.2.5" />
    <PackageReference Include="Avalonia.Skia" Version="11.2.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\payload.zip" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlumbobForge.Installer.Shared\PlumbobForge.Installer.Shared.csproj" />
  </ItemGroup>

</Project>
